import 'package:chore/chore.dart';
import 'package:strink/strink.dart';

/// Generates a `codecov.yaml` file.
String generateCodecovYaml({required Iterable<Package> packages}) {
  final buffer = StringBuffer();
  final writer = YamlSink(buffer);

  writer.writeComment('Generated by `chore`.');
  writer.writeNewline();

  writer.writeComment('https://docs.codecov.com/docs/carryforward-flags');
  writer.startObjectOrList('flags');
  for (final package in packages) {
    if (!package.supportsCoverage) {
      continue;
    }

    writer.startObjectOrList(package.name);
    writer.startObjectOrList('paths');
    writer.writeListValue('packages/${package.name}/**');
    writer.endObjectOrList();
    writer.writeKeyValue('carryforward', 'true');
    writer.endObjectOrList();
  }

  return buffer.toString();
}
