# Format: https://dart.dev/tools/pub/pubspec.

# Intentionally have an illegal name, we aren't publishing this package.
# ignore: package_names
name: pub.lurey.dev

# This is a workspace package and not intended to be published.
# See https://flutter.dev/go/pub-workspace for details.
publish_to: none
environment:
  sdk: ^3.5.0

workspace:
  - dev
  - packages/iota
  - packages/jsonut
  - packages/oath
  - packages/proc
  - packages/sdk
