# Format: https://dart.dev/tools/pub/pubspec.

# Intentionally have an illegal name, we aren't publishing this package.
# ignore: package_names
name: pub.lurey.dev

# This is a workspace package and not intended to be published.
# See https://flutter.dev/go/pub-workspace for details.
publish_to: none
environment:
  sdk: ^3.6.0

workspace:
  - dev
  - packages/chaos
  - packages/chore
  - packages/iota
  - packages/jsonut
  - packages/lore
  - packages/mansion
  - packages/oath
  - packages/proc
  - packages/quirk
  - packages/sdk
  - packages/strink
  - packages/webby
