name: sdk

# Pub requires at 60 chartacters or we are dinged for "too short".
# https://dart.dev/tools/pub/pubspec#description
description: Utilities for finding and using the Dart SDK programmatically.

# Not ready for publishing yet.
publish_to: none

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/sdk
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-sdk

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  async: ^2.11.0
  intl: ^0.19.0
  jsonut: ^0.4.1+2
  meta: ^1.16.0
  path: ^1.9.0
  proc: ^0.2.0

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.8
