name: oath
description: Swear a Paladin's Oath to code righteousness by enforcing lints.
version: 0.2.0-dev
repository: https://github.com/matanlurey/oath.dart

environment:
  sdk: ^3.4.0

dependencies:
  async: ^2.11.0
  lints: ^4.0.0
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_static: ^1.1.2

dev_dependencies:
  coverage: ^1.8.0
  test: ^1.25.7
