name: oath
description: Swear a Paladin's Oath to code righteousness by enforcing lints.
version: 0.2.0
repository: https://github.com/matanlurey/oath.dart

environment:
  sdk: ^3.4.0

dependencies:
  lints: ^4.0.0
