name: oath

# However, a shorter description is often better for a quick summary, so we
# store an unofficial shorter description as `short_description` which tools
# can optionally use.
#
# However, a shorter description is often better for a quick summary, so we
# store an unofficial shorter description as `short_description` which tools
# can optionally use.
description: Swear a Paladin's Oath to code righteousness by enforcing lints.
short_description: Strict linting for Dart packages.

version: 0.2.2

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/oath
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-oath

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  lints: ^5.1.0
  test: ^1.25.2
