name: oath
description: Swear a Paladin's Oath to code righteousness by enforcing lints.
version: 0.2.1+1

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/oath
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-oath

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  lints: ^4.0.0
  test: ^1.25.2
