/// The expected first 10 integers generated by Xoshiro128+.
///
/// The initial state of the generator must be set to `[1, 2, 3, 4]`.
const xoshiro128P$0_1_2_4$first10Integers = [
  5,
  12295,
  25178119,
  27286542,
  39879690,
  1140358681,
  3276312097,
  4110231701,
  399823256,
  2144435200,
];

/// The expected next 10 integers generated by Xoshiro128+ after jumping.
///
/// The initial state of the generator must be set to `[1, 2, 3, 4]`.
const xoshiro128P$0_1_2_4$jump$next10Integers = <int>[
  2887920503,
  1583871485,
  1223031203,
  350630958,
  1275758957,
  3520893674,
  2089251829,
  539808940,
  1683025647,
  1353992420,
];

/// The expected next 10 integers generated by Xoshiro128+ after long jumping.
///
/// The initial state of the generator must be set to `[1, 2, 3, 4]`.
const xoshiro128P$0_1_2_4$longJump$next10Integers = <int>[
  510881524,
  4189888193,
  4065621604,
  3656018618,
  2940187679,
  3975336349,
  491853863,
  1796559228,
  3497626486,
  3939701726,
];

/// The expected first 10 integers generated by Xoshiro128++.
///
/// The initial state of the generator must be set to `[1, 2, 3, 4]`.
const xoshiro128PP$0_1_2_4$first10Integers = [
  641,
  1573767,
  3222811527,
  3517856514,
  836907274,
  4247214768,
  3867114732,
  1355841295,
  495546011,
  621204420,
];

/// The expected next 10 integers generated by Xoshiro128++ after jumping.
///
/// The initial state of the generator must be set to `[1, 2, 3, 4]`.
const xoshiro128PP$0_1_2_4$jump$next10Integers = <int>[
  3129740764,
  111290574,
  1158071106,
  1835317750,
  1792746261,
  130735218,
  326039554,
  1024861044,
  3423294072,
  4108966210,
];

/// The expected next 10 integers generated by Xoshiro128++ after long jumping.
///
/// The initial state of the generator must be set to `[1, 2, 3, 4]`.
const xoshiro128PP$0_1_2_4$longJump$next10Integers = <int>[
  2580293941,
  2135890358,
  163124449,
  1843864296,
  1015915734,
  4033214785,
  401910505,
  1420128893,
  3902659533,
  508088920,
];
