# Format: https://dart.dev/tools/pub/pubspec

name: strukt

# However, a shorter description is often better for a quick summary, so we
# store an unofficial shorter description as `short_description` which tools
# can optionally use.
description: |-
  Decode, encode, and define structured data in multiple extensible formats.
short_description: Structured data.

version: 0.1.0-alpha

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/strukt
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-strukt

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.7
