# Format: https://dart.dev/tools/pub/pubspec

name: iota

# However, a shorter description is often better for a quick summary, so we
# store an unofficial shorter description as `short_description` which tools
# can optionally use.
#
# However, a shorter description is often better for a quick summary, so we
# store an unofficial shorter description as `short_description` which tools
# can optionally use.
description: |-
  Minimalist file system API which is compatible with sandboxes.
short_description: Minimalist file system API.

version: 0.0.0

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/iota
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-iota

resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  meta: ^1.15.0
  path: ^1.9.0

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.7
