# Format: https://dart.dev/tools/pub/pubspec

name: sector
description: |-
  Fast and intuitive 2D data structures: grids, graphs, pathfinding & more.
version: 0.3.0-alpha+2

environment:
  sdk: ^3.4.0

repository: https://github.com/matanlurey/sector.dart

dependencies:
  lodim: ^0.1.1+1
  meta: ^1.15.0

dev_dependencies:
  args: ^2.5.0
  benchmark_harness: ^2.2.2
  checks: ^0.3.0
  collection: ^1.19.0
  coverage: ^1.8.0
  oath:
    git:
      url: https://github.com/matanlurey/oath.dart
      ref: tools
  path: ^1.9.0
  test: ^1.25.8
