# Format: https://dart.dev/tools/pub/pubspec

name: sector
description: Fast and intuitive 2D Grid and grid-based utilities for Dart.
version: 0.1.1

environment:
  sdk: ^3.4.0

repository: https://github.com/matanlurey/sector

dependencies:
  meta: ^1.15.0

dev_dependencies:
  args: ^2.5.0
  benchmark_harness: ^2.2.2
  checks: ^0.3.0
  coverage: ^1.8.0
  oath:
    git:
      url: https://github.com/matanlurey/oath.dart
      ref: 597a39fb6aef4e052e419c914a5ea17880327e2a
  path: ^1.9.0
  test: ^1.25.7
