# Format: https://dart.dev/tools/pub/pubspec

name: proc

description: |-
  Run and manage OS processes with an extensible and testable API.
version: 0.2.0+1

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/proc
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-proc

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.15.0
  path: ^1.9.0

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.7
