# Format: https://dart.dev/tools/pub/pubspec

name: proc

description: |-
  Run and manage processes, including a record/replay mode for testing.
version: 0.0.0
repository: https://github.com/matanlurey/proc.dart

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.15.0

dev_dependencies:
  checks: ^0.3.0
  oath: ^0.2.1
  path: ^1.9.0
  test: ^1.25.7
