# Format: https://dart.dev/tools/pub/pubspec

name: trove

# However, a shorter description is often better for a quick summary, so we
# store an unofficial shorter description as `short_description` which tools
# can optionally use.
description: |-
  A collection of tools and components around playing cards and tabletop games
short_description: Tools for tabletop games

version: 0.1.0-alpha+1

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/trove
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-trove

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.15.0
  omen: ^0.1.1-alpha
  quirk: ">=0.1.2 <=0.3.0-alpha"

dev_dependencies:
  chaos: ^0.1.2+3
  checks: ^0.3.0
  test: ^1.25.7
