# Format: https://dart.dev/tools/analysis#the-analysis-options-file.

include: package:oath/strict.yaml

linter:
  rules:
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - sized_box_for_whitespace
    - sort_child_properties_last
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
