# Format: https://dart.dev/tools/pub/pubspec

name: lodim
description: |-
  Fixed-point pixel accurate 2D geometry with minimal approximations.
short_description: Fixed-point 2D geometry.

version: 0.1.6+5

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/lodim
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-lodim

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.15.0
  quirk: ">=0.1.2 <=0.3.0-alpha"

dev_dependencies:
  args: ^2.5.0
  benchmark_harness: ^2.2.2
  checks: ^0.3.0
  coverage: ^1.8.0
  path: ^1.9.0
  test: ^1.25.7
