# Format: https://dart.dev/tools/pub/pubspec

name: lodim
description: |-
  Fixed-point pixel accurate 2D geometry with minimal approximations.
version: 0.1.3

environment:
  sdk: ^3.5.0

repository: https://github.com/matanlurey/lodim

dependencies:
  meta: ^1.15.0

dev_dependencies:
  args: ^2.5.0
  benchmark_harness: ^2.2.2
  checks: ^0.3.0
  coverage: ^1.8.0
  oath: ^0.2.1
  path: ^1.9.0
  test: ^1.25.7
