# Format: https://dart.dev/tools/pub/pubspec

name: scrawl

description: |-
  Encode and decode structured messages with support for popular formats.
short_description: Structured messages.

publish_to: none

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/scrawl
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-scrawl

resolution: workspace

environment:
  sdk: ^3.7.0

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.7
dependencies:
  meta: ^1.16.0
