# Format: https://dart.dev/tools/pub/pubspec

name: codex

description: |-
  Encode and decode structured messages with support for popular formats.
short_description: Structured messages.

publish_to: none

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/codex
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-codex

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  armory: 0.1.0-alpha
  meta: ^1.16.0

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.7

