# Format: https://dart.dev/tools/pub/pubspec

name: jsonut
description: A minimal utility kit for working with JSON in a typesafe manner.
version: 0.4.1+2

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/jsonut
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-jsonut

resolution: workspace

environment:
  sdk: ^3.5.0

dev_dependencies:
  benchmark_harness: ^2.2.2
  checks: ^0.3.0
  test: ^1.25.2
