# Format: https://dart.dev/tools/pub/pubspec

name: chore

# However, a shorter description is often better for a quick summary, so we
# store an unofficial shorter description as `short_description` which tools
# can optionally use.
#
# However, a shorter description is often better for a quick summary, so we
# store an unofficial shorter description as `short_description` which tools
# can optionally use.
description: |-
  Opinionated open source project management tools for Dart packages.
short_description: Opinionated project management.

# Not ready to publish.
publish_to: none
version: 0.0.0

environment:
  sdk: ^3.5.0

repository: https://github.com/matanlurey/chore.dart
resolution: workspace

dependencies:
  args: ^2.5.0
  lore:
    path: ../lore
  meta: ^1.16.0
  path: ^1.9.0
  proc: ^0.2.0+1
  sdk:
    path: ../sdk

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.8

executables:
  chore:
