# Format: https://dart.dev/tools/pub/pubspec

name: chore
description: |-
  A minimalistic task runner for managing Dart and Flutter projects.
version: 0.0.0

environment:
  sdk: ^3.4.0

repository: https://github.com/matanlurey/chore.dart

dependencies:
  async: ^2.11.0
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_static: ^1.1.2

dev_dependencies:
  args: ^2.5.0
  checks: ^0.3.0
  coverage: ^1.8.0
  oath: ^0.2.0
  test: ^1.25.8

executables:
  chore:
