# Format: https://dart.dev/tools/pub/pubspec

name: webby

# Pub requires at 60 chartacters or we are dinged for "too short".
# https://dart.dev/tools/pub/pubspec#description
#
# However, a shorter description is often better for a quick summary, so we
# store an unofficial shorter description as `short_description` which tools
# can optionally use.
description: |-
  Artisnal hand-crafted interopability library for the web platform.
short_description: Hand-crafted interop for web apps.

version: 0.1.0-alpha+2

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/webby
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-webby

resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  meta: ^1.15.0

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.7
