# Format: https://dart.dev/tools/pub/pubspec

name: webby

description: |-
  An artisnal hand-crafted interopability library for the web platform.
version: 0.1.0-alpha

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/webby
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-webby

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.15.0

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.7
