# Format: https://dart.dev/tools/pub/pubspec

name: armory

description: |-
  An extended and curated set of data structures and algorithms.
short_description: More data structures

version: 0.1.0-alpha+1

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/armory
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-armory

resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.7
