name: package/lore

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/package_lore.yaml
      - packages/lore/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: dart-lang/setup-dart@v1.6.5
      - run: dart pub get
      - run: ./dev.sh setup --packages packages/lore
      - run: ./dev.sh check --packages packages/lore
      - run: ./dev.sh generate --no-root --fail-if-changed --packages packages/lore
      - run: ./dev.sh test --packages packages/lore
      - run: ./dev.sh coverage --packages packages/lore
      - uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: lore
          file: packages/lore/coverage/lcov.info
          fail_ci_if_error: true
