name: package/webby

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/package_webby.yaml
      - packages/webby/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/webby
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: dart-lang/setup-dart@v1.6.5
      - uses: browser-actions/setup-chrome@v1.7.2
      - run: dart pub get
        working-directory: packages/webby
      - run: ./dev.sh check --packages packages/webby
      - run: ./dev.sh test --packages packages/webby
