name: package/oath

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/package_oath.yaml
      - packages/oath/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: dart-lang/setup-dart@v1.6.5
      - run: dart pub get
        working-directory: packages/oath
      - run: ./dev.sh check --packages packages/oath
      - run: ./dev.sh test --packages packages/oath
      - run: ./dev.sh coverage --packages packages/oath
      - uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: oath
          file: packages/oath/coverage/lcov.info
