name: package/jsonut

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/package_jsonut.yaml
      - packages/jsonut/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/jsonut
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dart-lang/setup-dart@v1.6.4
      - uses: browser-actions/setup-chrome@v1
      - run: dart pub get
      - run: dart format --output none --set-exit-if-changed .
      - run: dart analyze
      - run: dart test
