name: package/rune

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/package_rune.yaml
      - packages/rune/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: dart-lang/setup-dart@v1.6.5
      - run: dart pub get
      - run: ./dev.sh setup --packages packages/rune
      - run: ./dev.sh check --packages packages/rune
      - run: ./dev.sh generate --no-root --fail-if-changed --packages packages/rune
      - run: ./dev.sh test --packages packages/rune
      - run: ./dev.sh coverage --packages packages/rune
      - uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: rune
          file: packages/rune/coverage/lcov.info
          fail_ci_if_error: true
  publish:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: dart-lang/setup-dart@v1.6.5
      - run: dart pub get
        working-directory: packages/rune
      - run: ./dev.sh publish --packages packages/rune
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
