name: package/lore

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/package_lore.yaml
      - packages/lore/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: dart-lang/setup-dart@v1.6.5
      - run: dart pub get
        working-directory: packages/lore
      - run: ./dev.sh check --packages packages/lore
      - run: ./dev.sh test --packages packages/lore
      - run: ./dev.sh coverage --packages packages/lore
      - uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/lore/coverage/lcov.info
