name: package/jsonut

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/package_jsonut.yaml
      - packages/jsonut/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/jsonut
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: dart-lang/setup-dart@v1.6.5
      - run: dart pub get
        working-directory: packages/jsonut
      - run: ./dev.sh check --packages packages/jsonut
      - run: ./dev.sh test --packages packages/jsonut
