name: package/sdk

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/package_sdk.yaml
      - packages/sdk/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: dart-lang/setup-dart@v1.6.5
      - run: dart pub get
        - run: ./dev.sh setup --packages packages/sdk
        - run: ./dev.sh check --packages packages/sdk
        - run: ./dev.sh test --packages packages/sdk
        - run: ./dev.sh coverage --packages packages/sdk
        - uses: codecov/codecov-action@v4.6.0
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            flags: sdk
            file: packages/sdk/coverage/lcov.info
            fail_ci_if_error: true
