name: package/chore

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/package_chore.yaml
      - packages/chore/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: dart-lang/setup-dart@v1.6.5
      - run: dart pub get
        working-directory: packages/chore
      - run: ./dev.sh check --packages packages/chore
      - run: ./dev.sh test --packages packages/chore
      - run: ./dev.sh coverage --packages packages/chore
      - uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/chore
          path-to-lcov: coverage/lcov.info
