# Format: https://dart.dev/tools/pub/pubspec

name: chaos
description: |-
  Fast and high quality pseudo-random number generators (PRNGs) with cloneable state.
version: 0.1.0
repository: https://github.com/matanlurey/chaos.dart
environment:
  sdk: ^3.4.0

dependencies:
  binary: 4.0.0-alpha+7
  meta: ^1.14.0

dev_dependencies:
  checks: ^0.3.0
  ffi: ^2.1.2
  oath: ^0.2.0
  path: ^1.9.0
  test: ^1.25.3
