# Format: https://dart.dev/tools/pub/pubspec

name: chaos

description: |-
  Fast and high quality pseudo-random number generators (PRNGs) with cloneable state.
short_description: High quality PRNGs

version: 0.1.2+1

homepage: https://github.com/matanlurey/pub.lurey.dev/tree/main/packages/chaos
issue_tracker: https://github.com/matanlurey/pub.lurey.dev/labels/pkg-chaos

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  binary: ^4.0.0
  meta: ^1.14.0

dev_dependencies:
  checks: ^0.3.0
  ffi: ^2.1.2
  oath: ^0.2.0
  path: ^1.9.0
  test: ^1.25.3
