name: CI

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]

jobs:
  build:
    defaults:
      run:
        working-directory: packages/sector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dart-lang/setup-dart@v1.6.4
      - run: dart pub get
      - run: ./chore.sh
      - run: dart format --output none --set-exit-if-changed .
      - run: dart analyze
      - run: dart pub global run chore coverage
      - name: Upload coverage
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: packages/sector/coverage/lcov.info
